### ISSUE TITLE
Configuration file

### ISSUE THREAD

**Issue by bpinto** [fish-shell/oh-my-fish#534] opened 2015-08-28 01:27 UTC
This is how we used to configure plugins and themes on the previous version:

```
Theme 'l'
Plugin 'brew'
Plugin 'boot2docker'
Plugin 'bundler'
Plugin 'cliniko'
Plugin 'dpaste'
Plugin 'extract'
Plugin 'rails'
Plugin 'random'
Plugin 'theme'
Plugin 'z'
Plugin 'rbenv'
```

With this new version, we have no way of keeping these configuration under version control. Well, apart from the theme which is stored here:

```
~/.config/omf/theme
```

BUT, even though the theme is stored, it's not downloaded automatically.

---

We need to at least keep the list of plugins on `~/.config/omf/plugins` as this would also allow us to download the packages when we do `omf install`.

**Comment by derekstavis** [comment] 2015-08-28 01:44
The absence of a configuration file in a versionable way is a serious problem and regression from what we had.

If I would design something from scratch that's extensible and powerful I would go with an approach similar to Bundler and NPM: Standardize a user file (the `Fishfile`) where dependencies are described.

Functions would be used to create a DSL for describing user dependencies:
```
plugin "foreign-env" "0.1" # install from tagged version
plugin "osx" "a87b7ef"     # install from specific commit
theme "agnoster"           # install and update from master
```

OMF framework then would be responsible for checking and satisfying dependencies, guided by a user command or by a shell boot-up, for example. `omf install` would check and immediately satisfy dependencies, if called without parameters.

**Comment by bucaran** [comment] 2015-08-28 05:54
> The absence of a configuration file in a versionable way is a serious problem and regression from what we had.

You have absolutely now idea about what you are talking about. Please read the source code of Oh My Fish! circa late 2014, then read Wahoo, then read Oh My Fish! a week ago and then read it again now.

> Fishfile then would be decreed the official file for dependency management.

I like this, but before we go this route, what about a more simple approach?

Currently we have:

```
~/.config/omf/theme
```

Which is just a file describing the current theme. We could easily change that to:

```
~/.config/omf/theme
~/.config/omf/plugins
```

**Comment by bpinto** [comment] 2015-08-28 10:42
Imo we need any approach right now.

I'd rather have a DSL that you can add in your fish file than to have the name of theme and packages in separate files (having the fish configuration in three different files).

But if it's going to be quicker to have a packages file and we can focus on the DSL discussion later, I'm all in.

Ping @bobthecow

**Comment by bucaran** [comment] 2015-08-28 10:47
Working on it. Simple approach, saving to $OMF_CONFIG

**Comment by bobthecow** [comment] 2015-08-28 16:32
I don't have a strong opinion on this one, other than whatever the config file is (manual or automatic) it actually persists between omf install/uninstall/reinstall cycles, and automatically installs my themes and plugins :)

**Comment by bpinto** [comment] 2015-08-31 22:15
So, to me we should restore OMF plugins and themes definition syntax. It keeps the configuration inside fish's and is quite simple to use.

@all opinions?

**Comment by derekstavis** [comment] 2015-09-01 00:43
I think this subject is urgent. The most time we spend on silent, more people are affected by the regression. Since the merge we need to come up quickly with ways to migrate from old stuff, or more issues like #520 will happen in the near future. This work ramped the last days with lots of people contributing with fixes and plugin ports, but core functionality must be restored.

As the PR, I'm inclined to spend my time with this, but we must move faster, at least until we reach feature compatibility with previous versions.

**Comment by scorphus** [comment] 2015-09-01 03:02
Until we won't come to a decision as to what the DSL will be – whether it'll include version/sha1/etc or not, or whatever – I think going back to latest OMF's themes definition syntax is a viable option.

I also can afford my spare time to solving this and the `omf update` issue.

**Comment by derekstavis** [comment] 2015-09-01 03:07
The solution via PR #564 is awaiting a merge for about 3 days, I don't understand why to screw the whole project it was so fast, while to merge a PR to fix the issues caused keeps hanging on while users which do `omf update` gets nervous.

**Comment by bpinto** [comment] 2015-09-01 11:48
#564 has been merged so we can add functionality to become backward compatible.

I want to avoid discussions, so let's not try to make another DSL for now. We can discuss this in the future. For now, let's add backwards compatibility using what we have in master.

**Comment by derekstavis** [comment] 2015-09-01 16:02
So should we close this issue now?

**Closed** 2015-09-01 16:04 UTC
Labels: idea
